"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let CW=2463534242,CB=()=>{let x=CW;x^=x<<13;x^=x>>>17;x^=x<<5;CW=x;return x;},Bt=f=>function(){return f(this);},Z=f=>function(p1,p2){return f(this,p1,p2);},Dh=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=O(Q(),args.length);for
(let i=0;i<args.length;++i){javaArgs.data[i]=Bi(args[i]);}D8(()=>{f.call(null,javaArgs);},callback);},Ck=target=>target.$clinit=()=>{},Ec=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0)
{superclass=Q();}return function(){superclass.call(this);};},BD=cls=>BT(cls),Q=()=>D,Bm=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Ee=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BP=(name,binaryName)=>{let cls=Ee();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},B6
=BP("char","C"),Bz=BP("int","I"),Dm=BP("void","V");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let Eh=BigInt(0),C3=val=>BigInt.asIntN(64,BigInt(val|0)),Df=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Dz=(a,b)=>a<=b,CM=(a,b)=>BigInt.asIntN(64,a+b),O=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bb(cls))(data);};
if(typeof BigInt64Array!=='function'){}else {}let Bs=sz=>new Ea(new Uint16Array(sz)),Dx=sz=>new CY(new Int32Array(sz)),G=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new CY(buffer);},Bb=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Q()).call(this);this.data=data;}JavaArray.prototype=Object.create((Q()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i)
{if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.N=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bb(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Q()],primitive:false,superclass:Q(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,
enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},BW,D4=strings=>{Ev();BW=new Array(strings.length);for(let i=0;i<strings.length;++i){BW[i]=CN(Bi(strings[i]));}},R=index=>BW[index],CK=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bi=str=>str===null?null:DL(str),Co=str=>str
===null?null:str.U,Ev=()=>(()=>{})(),CN;
{CN=str=>str;}let Ez=(obj,cls)=>obj instanceof Q()&&!!obj.constructor.$meta&&BL(obj.constructor,cls),BL=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&BL(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(BL(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},M=ex=>{throw Ew(ex);},BA=Symbol("javaException"),Ew=ex=>{let err=ex.$jsException;if(!err){let javaCause=Eq(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new N("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[BA]=ex;ex.$jsException=err;DO(err,ex);}return err;},DO
=(err,ex)=>{if(typeof DG==="function"&&err.stack){let stack=DG(err.stack);let javaStack=O(DY(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=D9(Bi(element.className),Bi(element.methodName),Bi(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Ej(ex,javaStack);}}},N;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");N=function N(message,cause){let self=Reflect.construct(Error,[void 0,cause],N);Object.setPrototypeOf(self,N.prototype);self[defaultMessage]=message;return self;}
;N.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:N},message:{get(){try {let javaException=this[BA];if(typeof javaException==='object'){let javaMessage=C9(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {N=Error;}let Dn=e=>e instanceof Error&&typeof e[BA]==='object'?e[BA]:null,C9=t=>El(t),Eq
=t=>Eu(t),DY=()=>Q(),D9=(className,methodName,fileName,lineNumber)=>{{return null;}},Ej=(e,stack)=>{},Cm=null,C_=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Cm=packages;},Cr=data=>{let packages=Cm;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex
=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo
===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func
=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},D8=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let CE=a=>{return;},EI=()=>{let a=new D();CE(a);return a;},Do=a=>{return BT(a.constructor);},Ef=a=>{let b,c,d,e,f,g,h,i,j,k,l,m;b=a;if(!b.$id$)b.$id$=CB();c=a.$id$;if(!c)d=R(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;e=g>>>4|0;if(!e)e=g;else f=f|4;g=e>>>2|0;if(!g)g=e;else f=f|2;if(g>>>1|0)f=f|1;e=(32-f|0)-1|0;}h=(((32-e|0)+4|0)-1|0)/4|0;i=Bs(h);j=i.data;h=(h-1|0)*4|0;e=0;while(h>=0){f=e+1|0;g=(c>>>h|0)&15;j[e]=g>=0&&g<16?(g<10?(48+g|0)&65535:((97+g|0)-10|0)&65535)
:0;h=h-4|0;e=f;}d=Dy(i);}b=new CA;b.W=Bs(16);CV(CV(b,R(1)),d);k=new P;i=b.W;j=i.data;l=b.ba;m=j.length;if(l>=0&&l<=(m-0|0)){k.U=CK(i.data,0,l);return k;}b=new Be;L(b);M(b);},ED=a=>{let b,c,d;if(!Ez(a,BX)&&a.constructor.$meta.item===null){b=new Cf;L(b);M(b);}b=DW(a);c=b;d=CB();c.$id$=d;return b;},B2=E(0),Ci=E(0);
function Ch(){D.call(this);this.bE=null;}
let BT=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new Ch;c.bE=b;b.classObject=c;}return c;},DN=a=>{return BT(a.bE.$meta.item);},DQ=E(),Bh=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},Ed=E(),DW=b=>{let copy=new b.constructor();for(let field in b){if(b.hasOwnProperty(field)){copy[field]=b[field];}}return copy;};
function BE(){let a=this;D.call(a);a.bP=null;a.b2=null;a.bS=0;a.bQ=0;}
let EH=a=>{return a;},El=a=>{return a.bP;},Eu=a=>{let b;b=a.b2;if(b===a)b=null;return b;},Bd=E(BE),L=a=>{a.bS=1;a.bQ=1;},EC=()=>{let a=new Bd();L(a);return a;},J=E(Bd),Dr=(a,b)=>{a.bS=1;a.bQ=1;a.bP=b;},EE=a=>{let b=new J();Dr(b,a);return b;},Et=E(J),S=E(0),Bk=E(0),BS=E(0),P=E(),Dl=null,Eb=null,DX=null,Dj=(a,b)=>{a.U=CK(b.data,0,b.data.length);},Dy=a=>{let b=new P();Dj(b,a);return b;},DT=(a,b)=>{a.U=b;},DL=a=>{let b=new P();DT(b,a);return b;},D0=()=>{let b;Dl=Bs(0);b=new P;b.U="";Eb=b;DX=new B5;},BN=E(),D1=E(BN),D7
=null,DU=()=>{D7=BD(Bz);};
function BV(){let a=this;D.call(a);a.W=null;a.ba=0;}
let Ds=(a,b)=>{let c,d,e,f,g;c=a.W.data.length;if(c>=b)return;d=c>=1073741823?2147483647:Bx(b,Bx(c*2|0,5));e=a.W.data;f=Bs(d);g=f.data;b=Cl(d,e.length);c=0;while(c<b){g[c]=e[c];c=c+1|0;}a.W=f;},C8=E(0),CA=E(BV),CV=(a,b)=>{let c,d,e,f,g,h,i;c=a.ba;d=a;b=b===null?R(2):b;e=d;if(c>=0&&c<=e.ba){a:{b:{if(b===null)b=R(2);else if(b.U.length?0:1)break b;f=e.ba+b.U.length|0;Ds(e,f);g=e.ba-1|0;while(g>=c){e.W.data[g+b.U.length|0]=e.W.data[g];g=g+(-1)|0;}e.ba=e.ba+b.U.length|0;f=0;while(f<b.U.length){h=e.W;i=c+1|0;if(f
<0)break a;if(f>=b.U.length)break a;h.data[c]=b.U.charCodeAt(f);f=f+1|0;c=i;}}return a;}M(Dq());}b=new BY;C6(b);M(b);},C0=E(),F=null,B0=null,BQ=0,H=()=>{H=Ck(C0);Dc();},Di=b=>{let c,d,e,f,g;H();if(BQ){Ep();BQ=0;return;}background(54,69,79);c=F;d=c.bB;e=0;a:{while(e<15){f=0;while(f<15){if(d.bn.data[f].data[e]==1){e=0;break a;}f=f+1|0;}e=e+1|0;}e=1;}if(e){c.Z=1;c.bs=1;}f=0;while(f<15){e=0;while(e<15){if(d.bn.data[e].data[f]==1){push();fill(255,255,255);noStroke();circle((f*57|0)+28|0,(e*57|0)+28|0,10.0);pop();}e
=e+1|0;}f=f+1|0;}f=0;while(f<15){g=0;while(g<15){if(d.bx.data[g].data[f]==1){fill(37,35,231);square(f*57|0,g*57|0,57);}g=g+1|0;}f=f+1|0;}c=F;d=c.bM;if(!c.Z)b:{if(c.bo){c=d.S;g=c.O;e=c.P-1|0;if(!Bf(d.be,g,e))e=0;else{d.S=K(g,e);e=1;}if(e)break b;}if(F.bt){c=d.S;e=c.O-1|0;g=c.P;if(!Bf(d.be,e,g))e=0;else{d.S=K(e,g);e=1;}if(e)break b;}if(F.bp){c=d.S;g=c.O;e=c.P+1|0;if(!Bf(d.be,g,e))e=0;else{d.S=K(g,e);e=1;}if(e)break b;}if(F.br){c=d.S;e=c.O+1|0;g=c.P;if(Bf(d.be,e,g))d.S=K(e,g);}}c=d.S;movePlayer(c.O*57|0,c.P*57
|0);c=d.be;d=d.S;c.bn.data[d.P].data[d.O]=0;Dv(F.bK);(Es(F)).l();c=F;if(c.bz){d=Cn(c.Q);F=d;d.Z=0;d.bc=0;d.bs=0;}Er();},Ep=()=>{let b,c;H();F=Cn(6);createCanvas(855.0,855.0);b=window.document.getElementById("canvas");c=new BH;b.addEventListener("mousemove",Bh(Bg(c),"handleEvent"));c=new BF;b.addEventListener("mousedown",Bh(Bg(c),"handleEvent"));c=new BG;b.addEventListener("mouseup",Bh(Bg(c),"handleEvent"));c=new BI;b.addEventListener("dblclick",Bh(Bg(c),"handleEvent"));c=new BU;b.addEventListener("keyup",Bh(Bg(c),
"handleEvent"));},Er=()=>{let b;H();b=F;b.by=0;b.bo=0;b.bt=0;b.bp=0;b.br=0;b.bj=0;b.bq=0;b.bi=0;b.bl=0;b.bk=0;b.bm=0;b.bh=0;},Dc=()=>{D0();DU();DJ();D5();D$();B0=new Cc;BQ=1;},Ek=E(),CT=E(0),B5=E(),CZ=E(),D6=null,Ei=null,DJ=()=>{D6=BD(B6);Ei=O(CZ,128);},C4=E(0),Cc=E(),CS=(a,b)=>{let c;if(b<=0){c=new BB;L(c);M(c);}return DP()*b|0;},En=E();
function C1(){let a=this;D.call(a);a.b0=0;a.b1=0;a.bw=0;a.bt=0;a.bo=0;a.bp=0;a.br=0;a.bj=0;a.bq=0;a.bi=0;a.bl=0;a.bk=0;a.bm=0;a.bh=0;a.Z=0;a.bs=0;a.bc=0;a.bz=0;a.bB=null;a.bM=null;a.bK=null;a.by=0;a.Q=0;}
let B8=null,B4=null,Cb=null,Cg=null,DV=(a,b)=>{let c,d,e,f,g,h;a.bw=0;a.bt=0;a.bo=0;a.bp=0;a.br=0;a.bj=0;a.bq=0;a.bi=0;a.bl=0;a.bk=0;a.bm=0;a.bh=0;a.Z=1;a.bs=0;a.bc=1;a.bz=0;c=DR();a.bB=c;d=new Cd;d.bX=7;d.bW=13;e=K(7,13);d.S=e;d.be=c;f=e.O*57|0;g=e.P*57|0;movePlayer(f,g);a.bM=d;c=new CF;e=a.bB;h=new Cs;h.b7=c;c.bL=h;h=new Cu;h.b5=c;c.bJ=h;h=new Ct;h.b8=c;c.bT=h;h=new Cw;h.b6=c;c.bI=h;h=new Cv;h.b3=c;c.bR=h;h=new Cx;h.b9=c;c.bN=h;c.X=BC();c.Y=BC();c.bv=1;c.bF=d;c.bG=e;a.bK=c;a.by=0;a.Q=b;},Cn=a=>{let b=new C1();DV(b,
a);return b;},Es=a=>{if(a.bc)return Cg;if(a.bs)return B4;if(!a.Z)return Cb;return B8;},D5=()=>{B8=new B_;B4=new CC;Cb=new Cz;Cg=new B$;},Bp=E(0),B7=E(0),Ce=E(0),CU=E(0),Dd=E(),Bc=E(0),BH=E(),Ex=(b,c)=>{b;H();F.b0=c.clientX;F.b1=c.clientY;};
function CH(){D.call(this);this.b4=null;}
let Bg=b=>{if(b===null)return null;return !(b instanceof CH)?b:b.b4;},BF=E(),Eg=(b,c)=>{b;H();F.bw=1;},BG=E(),Dw=(b,c)=>{b;H();F.bw=0;},BI=E(),DH=(b,c)=>{b;H();F.by=1;},BU=E(),DE=(b,c)=>{b;a:{b:{c:{d:{e:{f:{g:{h:{switch(c.keyCode){case 32:H();F.bj=1;break h;case 49:break h;case 50:break g;case 51:break f;case 52:break e;case 53:break d;case 54:break c;case 65:break;case 68:H();F.br=1;break a;case 83:H();F.bp=1;break a;case 87:break b;default:break a;}H();F.bt=1;break a;}H();F.bq=1;}H();F.bi=1;}H();F.bl=1;}H();F.bk
=1;}H();F.bm=1;}H();F.bh=1;}H();F.bo=1;}},De=E();
function CD(){let a=this;D.call(a);a.bx=null;a.bn=null;}
let DB=a=>{let b,c;CE(a);b=O(Bb(Bz),15);c=b.data;c[0]=G([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);c[1]=G([1,0,0,0,0,0,0,1,0,0,0,0,0,0,1]);c[2]=G([1,0,1,0,1,1,0,1,0,1,1,0,1,0,1]);c[3]=G([1,0,0,0,0,0,0,0,0,0,0,0,0,0,1]);c[4]=G([1,0,0,0,1,0,1,1,1,0,1,0,1,0,1]);c[5]=G([1,1,1,0,1,0,0,1,0,0,1,0,1,0,1]);c[6]=G([1,0,0,0,1,1,0,0,0,1,1,0,0,0,1]);c[7]=G([1,0,1,0,1,0,0,0,0,0,1,0,1,0,1]);c[8]=G([1,0,1,0,0,0,1,1,1,0,0,0,1,0,1]);c[9]=G([1,0,0,1,1,0,0,0,0,0,1,1,0,0,1]);c[10]=G([1,1,0,0,0,0,1,1,1,0,0,0,0,1,1]);c[11]=G([1,0,0,0,1,0,0,
1,0,0,1,0,0,0,1]);c[12]=G([1,0,1,1,1,1,0,0,0,1,1,1,1,0,1]);c[13]=G([1,0,0,0,0,0,0,0,0,0,0,0,0,0,1]);c[14]=G([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);a.bx=b;b=O(Bb(Bz),15);c=b.data;c[0]=G([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);c[1]=G([0,1,1,1,1,1,1,0,1,1,1,1,1,1,0]);c[2]=G([0,1,0,1,0,0,1,0,1,0,0,1,0,1,0]);c[3]=G([0,1,1,1,1,1,1,1,1,1,1,1,1,1,0]);c[4]=G([0,1,1,1,0,1,0,0,0,1,0,1,0,1,0]);c[5]=G([0,0,0,1,0,1,1,0,1,1,0,1,0,1,0]);c[6]=G([0,1,1,1,0,0,1,1,1,0,0,1,1,1,0]);c[7]=G([0,1,0,1,0,1,1,1,1,1,0,1,0,1,0]);c[8]=G([0,1,0,1,1,1,
0,0,0,1,1,1,0,1,0]);c[9]=G([0,1,1,0,0,1,1,1,1,1,0,0,1,1,0]);c[10]=G([0,0,1,1,1,1,0,0,0,1,1,1,1,0,0]);c[11]=G([0,1,1,1,0,1,1,0,1,1,0,1,1,1,0]);c[12]=G([0,1,0,0,0,0,1,1,1,0,0,0,0,1,0]);c[13]=G([0,1,1,1,1,1,1,1,1,1,1,1,1,1,0]);c[14]=G([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);a.bn=b;},DR=()=>{let a=new CD();DB(a);return a;},Bo=(a,b,c)=>{let d;d=By(c);while(true){if(!Bq(d))return Bf(a,b.O,b.P);if(C5((Bv(d)).R,b))break;}return 0;},Bf=(a,b,c)=>{return a.bx.data[c].data[b]?0:1;};
function Cd(){let a=this;D.call(a);a.bX=7;a.bW=13;a.S=null;a.be=null;}
function CF(){let a=this;D.call(a);a.bL=null;a.bJ=null;a.bT=null;a.bI=null;a.bR=null;a.bN=null;a.bF=null;a.bG=null;a.X=null;a.Y=null;a.bv=0;}
let D3=a=>{let b,c,d,e,f,g;b=Ba(a.bL,X(K(8,7)));I(a.X,b);I(a.Y,b.T);H();if(F.Q>1){c=Ba(a.bJ,X(K(6,6)));I(a.X,c);I(a.Y,c.T);}if(F.Q>2){d=Ba(a.bT,X(K(6,7)));I(a.X,d);I(a.Y,d.T);}if(F.Q>3){e=Ba(a.bI,X(K(8,6)));I(a.X,e);I(a.Y,e.T);}if(F.Q>4){f=Ba(a.bR,X(K(7,7)));I(a.X,f);I(a.Y,f.T);}if(F.Q>5){g=Ba(a.bN,X(K(7,6)));I(a.X,g);I(a.Y,g.T);}},Dv=a=>{let b,c,d,e;if(a.bv){D3(a);a.bv=0;}b=By(a.X);while(Bq(b)){c=Bv(b);CR(a,c);H();if(F.Z){d=c.bD;c=c.T.R;d.C(c.O*57|0,c.P*57|0);}else{d=a.bG;e=a.Y;Dk(c.T,d,e);e=c.T.R;c.bD.C(e.O
*57|0,e.P*57|0);CR(a,c);}}},CR=(a,b)=>{if(C5(b.T.R,a.bF.S)){H();F.Z=1;}},Be=E(J),C6=a=>{L(a);},EG=()=>{let a=new Be();C6(a);return a;};
function U(){let a=this;D.call(a);a.O=0;a.P=0;}
let Bj=(a,b,c)=>{a.O=b;a.P=c;},K=(a,b)=>{let c=new U();Bj(c,a,b);return c;},C5=(a,b)=>{let c;if(a===b)return 1;if(b===null)return 0;if(!(b instanceof U))return 0;c=b;return c.O==a.O&&c.P==a.P?1:0;},T=E(0);
function Cs(){D.call(this);this.b7=null;}
let Dg=(a,b,c)=>{moveEnemyRed(b,c);};
function Cu(){D.call(this);this.b5=null;}
let Em=(a,b,c)=>{moveEnemyBlue(b,c);};
function Ct(){D.call(this);this.b8=null;}
let Dt=(a,b,c)=>{moveEnemyPink(b,c);};
function Cw(){D.call(this);this.b6=null;}
let Du=(a,b,c)=>{moveEnemyOrange(b,c);};
function Cv(){D.call(this);this.b3=null;}
let DC=(a,b,c)=>{moveEnemyGreen(b,c);};
function Cx(){D.call(this);this.b9=null;}
let D2=(a,b,c)=>{moveEnemyPurple(b,c);},B3=E(0),BJ=E(0),BK=E(),Cp=E(0),CO=E(0);
function BO(){BK.call(this);this.bf=0;}
let By=a=>{let b;b=new CG;b.bO=a;b.bU=a.bf;b.bH=a.V;b.bV=(-1);return b;},BX=E(0),Cq=E(0);
function Br(){let a=this;BO.call(a);a.bb=null;a.V=0;}
let Ca=a=>{a.bb=O(D,10);},BC=()=>{let a=new Br();Ca(a);return a;},DI=(a,b)=>{let c,d,e,f,g;c=a.bb.data.length;if(c<b){d=c>=1073741823?2147483647:Bx(b,Bx(c*2|0,5));e=a.bb;f=DN(Do(e));if(f===null){f=new Cy;L(f);M(f);}if(f===BD(Dm)){f=new BB;L(f);M(f);}if(d<0){f=new C7;L(f);M(f);}g=e.data;e=DM(f.bE,d);b=Cl(d,g.length);d=0;while(d<b){e.data[d]=g[d];d=d+1|0;}a.bb=e;}},DS=(a,b)=>{CI(a,b);return a.bb.data[b];},EB=a=>{return a.V;},I=(a,b)=>{let c,d;DI(a,a.V+1|0);c=a.bb.data;d=a.V;a.V=d+1|0;c[d]=b;a.bf=a.bf+1|0;return 1;},CI
=(a,b)=>{let c;if(b>=0&&b<a.V)return;c=new Be;L(c);M(c);},Bl=E(0),B_=E(),Db=a=>{let b;push();fill(255,116,108);square(277,277,300);fill(0,0,0);text("GAME OVER!\nPress SPACE to restart.",427,427);pop();H();b=F;if(b.bj)b.bc=1;},CC=E(),DA=a=>{let b;push();fill(119,221,119);square(277,277,300);fill(0,0,0);text("YOU WON!\nPress SPACE to restart.",427,427);pop();H();b=F;if(b.bj)b.bc=1;},Cz=E(),Eo=a=>{return;},B$=E(),D_=a=>{let b,c;push();fill(174,198,207);square(277,277,300);fill(0,0,0);text("New Game\nWASD to move\nSelect difficulty by pressing\none of the following numbers\n1\n2\n3\n4\n5\n6",
427,377);pop();H();b=F;c=b.bq;if(!(!c&&!b.bi&&!b.bl&&!b.bk&&!b.bm&&!b.bh)){b.bc=0;b.Z=0;b.bz=1;}if(c)b.Q=1;else if(b.bi)b.Q=2;else if(b.bl)b.Q=3;else if(b.bk)b.Q=4;else if(b.bm)b.Q=5;else if(b.bh)b.Q=6;},BB=E(J);
function C2(){let a=this;D.call(a);a.bD=null;a.T=null;}
let C$=(a,b,c)=>{a.bD=b;a.T=c;},Ba=(a,b)=>{let c=new C2();C$(c,a,b);return c;};
function CJ(){let a=this;D.call(a);a.bA=Eh;a.R=null;a.bg=null;a.bu=null;}
let Da=(a,b)=>{let c,d,e;a.bg=null;c=new CL;c.bZ=a;Ca(c);d=V;e=c;I(e,d);I(e,W);I(e,Y);I(e,Bn);a.bu=c;a.R=b;H();a.bA=CM(BM(),C3(CS(B0,1500)+1000|0));},X=a=>{let b=new CJ();Da(b,a);return b;},Dk=(a,b,c)=>{let d,e,f,g,h,i,j,k;if(Dz(BM(),a.bA))return;a.bA=CM(BM(),C3(300));d=a.bu;e=BC();while(!(d.V?0:1)){H();f=CS(B0,d.V);CI(d,f);g=d.bb.data;h=g[f];i=d.V-1|0;d.V=i;while(f<i){j=f+1|0;g[f]=g[j];f=j;}g[i]=null;d.bf=d.bf+1|0;I(e,h);}h=By(e);while(Bq(h)){I(d,Bv(h));}f=0;while(f<2){k=By(a.bu);while(Bq(k)){a:{d=Bv(k);BZ();switch
(B9.data[d.bd]){case 1:break;case 2:e=V;break a;case 3:e=Bn;break a;case 4:e=Y;break a;default:e=null;break a;}e=W;}j=a.bg!==e?0:1;if(j&&!f)continue;if(Bu(d,Y)){e=new U;h=a.R;Bj(e,h.O-1|0,h.P);if(Bo(b,e,c)){a.R=e;a.bg=d;return;}}if(Bu(d,Bn)){e=new U;h=a.R;Bj(e,h.O+1|0,h.P);if(Bo(b,e,c)){a.R=e;a.bg=d;return;}}if(Bu(d,V)){e=new U;h=a.R;Bj(e,h.O,h.P-1|0);if(Bo(b,e,c)){a.R=e;a.bg=d;return;}}if(Bu(d,W)){e=new U;h=a.R;Bj(e,h.O,h.P+1|0);if(Bo(b,e,c)){a.R=e;a.bg=d;return;}}}f=f+1|0;}};
function CL(){Br.call(this);this.bZ=null;}
let DK=E(),BM=()=>{return Df((new Date()).getTime());};
function BR(){let a=this;D.call(a);a.bY=null;a.bd=0;}
let Bu=(a,b)=>{return a!==b?0:1;},B1=E(BR),V=null,W=null,Y=null,Bn=null,CX=null,DD=(a,b,c)=>{a.bY=b;a.bd=c;},Bw=(a,b)=>{let c=new B1();DD(c,a,b);return c;},D$=()=>{let b,c,d;V=Bw(R(3),0);W=Bw(R(4),1);Y=Bw(R(5),2);b=Bw(R(6),3);Bn=b;c=O(B1,4);d=c.data;d[0]=V;d[1]=W;d[2]=Y;d[3]=b;CX=c;},CQ=E(0);
function CG(){let a=this;D.call(a);a.bC=0;a.bU=0;a.bH=0;a.bV=0;a.bO=null;}
let Bq=a=>{return a.bC>=a.bH?0:1;},Bv=a=>{let b,c,d;b=a.bU;c=a.bO;if(b<c.bf){c=new Cj;L(c);M(c);}d=a.bC;a.bV=d;a.bC=d+1|0;return DS(c,d);},DF=E(),DP=()=>{return Math.random();},Cl=(b,c)=>{if(b<c)c=b;return c;},Bx=(b,c)=>{if(b>c)c=b;return c;},Ey=E(),Cj=E(J),Dp=E(),DM=(b,c)=>{if(b.$meta.primitive){switch(b){};}return O(b,c);},Cy=E(J),C7=E(J),BY=E(Be),EA=a=>{L(a);},Dq=()=>{let a=new BY();EA(a);return a;},CP=E(),B9=null,BZ=()=>{BZ=Ck(CP);DZ();},DZ=()=>{let b,c;b=Dx((CX.N()).data.length);c=b.data;B9=b;c[V.bd]=1;c[W.bd]
=2;c[Y.bd]=3;c[Bn.bd]=4;},Cf=E(Bd);
C_([]);
Cr([D,0,0,[],0,3,0,0,0,B2,0,D,[],3,3,0,0,0,Ci,0,D,[],3,3,0,0,0,Ch,0,D,[B2,Ci],4,3,0,0,0,DQ,0,D,[],4,3,0,0,0,Ed,0,D,[],4,3,0,0,0,BE,0,D,[],0,3,0,0,0,Bd,0,BE,[],0,3,0,0,0,J,0,Bd,[],0,3,0,0,0,Et,0,J,[],0,3,0,0,0,S,0,D,[],3,3,0,0,0,Bk,0,D,[],3,3,0,0,0,BS,0,D,[],3,3,0,0,0,P,0,D,[S,Bk,BS],0,3,0,0,0,BN,0,D,[S],1,3,0,0,0,D1,0,BN,[Bk],0,3,0,0,0,BV,0,D,[S,BS],0,0,0,0,0,C8,0,D,[],3,3,0,0,0,CA,0,BV,[C8],0,3,0,0,0,C0,0,D,[],0,3,0,H,0,Ek,0,D,[],4,3,0,0,0,CT,0,D,[],3,3,0,0,0,B5,0,D,[CT],0,3,0,0,0,CZ,0,D,[Bk],0,3,0,0,0,C4,
0,D,[],3,3,0,0,0,Cc,0,D,[C4,S],0,3,0,0,0,En,0,D,[],0,3,0,0,0,C1,0,D,[],0,3,0,0,0,Bp,0,D,[],3,3,0,0,0,B7,0,D,[Bp],3,3,0,0,0,Ce,0,D,[B7],3,3,0,0,0,CU,0,D,[Bp],3,3,0,0,0,Dd,0,D,[Ce,CU],1,3,0,0,0,Bc,0,D,[Bp],3,3,0,0,0,BH,0,D,[Bc],0,3,0,0,0,CH,0,D,[],4,3,0,0,0,BF,0,D,[Bc],0,3,0,0,0,BG,0,D,[Bc],0,3,0,0,0,BI,0,D,[Bc],0,3,0,0,0,BU,0,D,[Bc],0,0,0,0,0,De,0,D,[],4,3,0,0,0,CD,0,D,[],0,3,0,0,0,Cd,0,D,[],0,3,0,0,0,CF,0,D,[],0,3,0,0,0,Be,0,J,[],0,3,0,0,0,U,0,D,[],0,3,0,0,0,T,0,D,[],3,3,0,0,0,Cs,0,D,[T],0,0,0,0,["C",Z(Dg)],Cu,
0,D,[T],0,0,0,0,["C",Z(Em)],Ct,0,D,[T],0,0,0,0,["C",Z(Dt)]]);
Cr([Cw,0,D,[T],0,0,0,0,["C",Z(Du)],Cv,0,D,[T],0,0,0,0,["C",Z(DC)],Cx,0,D,[T],0,0,0,0,["C",Z(D2)],B3,0,D,[],3,3,0,0,0,BJ,0,D,[B3],3,3,0,0,0,BK,0,D,[BJ],1,3,0,0,0,Cp,0,D,[BJ],3,3,0,0,0,CO,0,D,[Cp],3,3,0,0,0,BO,0,BK,[CO],1,3,0,0,0,BX,0,D,[],3,3,0,0,0,Cq,0,D,[],3,3,0,0,0,Br,0,BO,[BX,S,Cq],0,3,0,0,0,Bl,0,D,[],3,3,0,0,0,B_,0,D,[Bl],0,3,0,0,["l",Bt(Db)],CC,0,D,[Bl],0,3,0,0,["l",Bt(DA)],Cz,0,D,[Bl],0,3,0,0,["l",Bt(Eo)],B$,0,D,[Bl],0,3,0,0,["l",Bt(D_)],BB,0,J,[],0,3,0,0,0,C2,0,D,[],0,0,0,0,0,CJ,0,D,[],0,3,0,0,0,CL,0,
Br,[],0,0,0,0,0,DK,0,D,[],4,3,0,0,0,BR,0,D,[Bk,S],1,3,0,0,0,B1,0,BR,[],12,0,0,0,0,CQ,0,D,[],3,3,0,0,0,CG,0,D,[CQ],0,0,0,0,0,DF,0,D,[],4,3,0,0,0,Ey,0,D,[],0,3,0,0,0,Cj,0,J,[],0,3,0,0,0,Dp,0,D,[],4,3,0,0,0,Cy,0,J,[],0,3,0,0,0,C7,0,J,[],0,3,0,0,0,BY,0,Be,[],0,3,0,0,0,CP,0,D,[],32,0,0,BZ,0,Cf,0,Bd,[],0,3,0,0,0]);
let Ea=Bb(B6),CY=Bb(Bz);
D4(["0","<java_object>@","null","UP","DOWN","LEFT","RIGHT"]);
P.prototype.toString=function(){return Co(this);};
P.prototype.valueOf=P.prototype.toString;D.prototype.toString=function(){return Co(Ef(this));};
D.prototype.__teavm_class__=function(){return Ec(this);};
let C=Dh(Di);
C.javaException=Dn;
let EF=Symbol('jsoClass');
(()=>{let c;c=BH.prototype;c.handleEvent=Bm(Ex);c=BF.prototype;c.handleEvent=Bm(Eg);c=BG.prototype;c.handleEvent=Bm(Dw);c=BI.prototype;c.handleEvent=Bm(DH);c=BU.prototype;c.handleEvent=Bm(DE);})();
B.main=C;}));
